title: LTW GCR Project
theme: jekyll-theme-cayman
description: Global Cybersecurity Resource (GCR) is a not-for-profit project organization run by Carleton University’s Lead to Win (LTW) program.  The organization is mandated with increasing the IT security of Ottawa region SMEs, increasing the availability of qualified security staff, and driving economic development for existing and new companies. 
